### PR TITLE
Cancellable animations (for async methods) + Expander fix

### LINKED ISSUE #5851: Confuse `Expander`
**To Reproduce**

1. Go to an Expander
image
2. Open it.
image
3. Double click on it.
image

Arrow says it is open, but not. Need to click twice to open it again.

### PR DESCRIPTION
**Pull request by maxkatz6**
## What is the current behavior?
It's not possible to cancel animation/pagetransition using async methods.
It causes issues on some controls (see https://github.com/AvaloniaUI/Avalonia/issues/5851)

## What is the updated/expected behavior with this PR?

- It is possible to cancel animation/pagetransition using async methods.
- Also actually cancels animation on page transition for Expander and TransitioningContentControl controls.
- Fixes CrossFade to not set local values when it's not necessary.

## Checklist

I am planning to add some unit tests next weekend.

- [ ] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

Yes. New "CancellationToken" parameter was added parameter to some methods.

## Fixed issues
Fixes #5851

### CODE REVIEW

**Comment by maxkatz6** [comment]
I with there was any way to add new parameter without breaking compatibility (in would break it in any way - adding new method or changing old one). Default interface methods might help here, but we can't use it with current target. Though from API perspective single cancellable method is better.
Though I prefer Animation.RunAsync to be an extension method. But it uses IterationCount prop which is not part of the interface. Cleaner to leave it as it is.

**Review by jmacato — APPROVED** [review]
LGTM

File: src/Avalonia.ReactiveUI/TransitioningContentControl.cs [hunk 1]
```diff
@@ -62,11 +66,14 @@ public class TransitioningContentControl : ContentControl, IStyleable
         /// <param name="content">New content to set.</param>
         private async void UpdateContentWithTransition(object? content)
         {
+            _lastTransitionCts?.Cancel();
```
Comment (Takoooooo) [inline src/Avalonia.ReactiveUI/TransitioningContentControl.cs:69]: Dispose()?

File: src/Avalonia.Visuals/Animation/CrossFade.cs [hunk 2]
```diff
@@ -97,49 +99,39 @@ public Easing FadeOutEasing
...
-
-            if (from != null)
+            if (cancellationToken.IsCancellationRequested)
             {
-                tasks.Add(_fadeOutAnimation.RunAsync(from));
+                return;
             }
 
-            if (to != null)
+            var tasks = new List<Task>();
```
Comment (Takoooooo) [inline src/Avalonia.Visuals/Animation/CrossFade.cs:110]: this part looks strange to me. When we have only 1 task to await no need to use Task.WhenAll. When we have 2 tasks don't create a list, Task.WhenAll have overload which accepts params Task[].

File: src/Avalonia.ReactiveUI/TransitioningContentControl.cs (hunk 1 above)
Comment (maxkatz6) [reply src/Avalonia.ReactiveUI/TransitioningContentControl.cs:69]: No need. Token source was already cancelled and it didn't even kept a timer to dispose.

File: src/Avalonia.Visuals/Animation/CrossFade.cs (hunk 2 above)
Comment (maxkatz6) [reply src/Avalonia.Visuals/Animation/CrossFade.cs:110]: I wasn't changing previous code here, though it makes sense to optimize it for a bit like you said. Still it will also make code a bit more complex as well.

Comment (Takoooooo) [reply src/Avalonia.Visuals/Animation/CrossFade.cs:110]: sry haven't realized this code previously existed
