### PR TITLE
fix: [DevTools] Invalid property Editor for char property

### LINKED ISSUE #11708: [DevTools] InvalidCastException
**Describe the bug**
immagine

### StackTrace
```bash
>	Avalonia.Diagnostics.dll!Avalonia.Diagnostics.Views.PropertyValueEditorView.ValueToDecimalConverter.Convert(object value, System.Type targetType, object parameter, System.Globalization.CultureInfo culture) Line 374	C#
 	Avalonia.Diagnostics.dll!Avalonia.Diagnostics.Views.PropertyValueEditorView.ValueConverter.Avalonia.Data.Converters.IValueConverter.Convert(object value, System.Type targetType, object parameter, System.Globalization.CultureInfo culture) Line 275	C#
 	Avalonia.Base.dll!Avalonia.Data.Core.BindingExpression.ConvertValue(object value) Line 211	C#
 	Avalonia.Base.dll!Avalonia.Data.Core.BindingExpression.ConvertValue(Avalonia.Data.BindingNotification notification) Line 251	C#
 	Avalonia.Base.dll!Avalonia.Data.Core.BindingExpression.InnerListener.OnNext(object value) Line 360	C#
 	Avalonia.Base.dll!Avalonia.Reactive.LightweightObservableBase<object>.PublishNext(object value) Line 149	C#
 	Avalonia.Base.dll!Avalonia.Data.Core.Plugins.InpcPropertyAccessorPlugin.Accessor.SendCurrentValue() Line 178	C#
 	Avalonia.Base.dll!Avalonia.Data.Core.Plugins.InpcPropertyAccessorPlugin.Accessor.SubscribeCore() Line 156	C#
 	Avalonia.Base.dll!Avalonia.Data.Core.PropertyAccessorNode.StartListeningCore(System.WeakReference<object> reference) Line 83	C#
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Version: **11.0.0-rc1**

**Additional context**

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What does the pull request do?

Use `TextBox` as editor for `char` property.

## What is the current behavior?

DevTools throws InvalidCastException when property is `char` because it uses `NumericUpDown` as editor.

## How was the solution implemented (if it's not obvious)?

the source of the issue is the following code:

https://github.com/AvaloniaUI/Avalonia/blob/012aa1555a740437a9d3f2679d43d3eeafb660a6/src/Avalonia.Diagnostics/Diagnostics/Views/PropertyValueEditorView.cs#L95-L105

to check if property type is valid for NumericUpDown, check that `propertyType` is primitive type and not `float` or `double`, but `char` type also satisfies condition.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #11708

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0036673-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0036690-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

File: src/Avalonia.Diagnostics/Diagnostics/Views/PropertyValueEditorView.cs [hunk 1]
```diff
@@ -261,6 +231,74 @@ private static bool ImplementsInterface<TInterface>(Type type)
             }
 
             return tb;
+
+            TControl CreateControl<TControl>(AvaloniaProperty valueProperty
```
Comment (robloo) [inline src/Avalonia.Diagnostics/Diagnostics/Views/PropertyValueEditorView.cs:235]: A few nits here about formatting.

 1. Technically there is a formatting rule some place where either all parameters should be on one line or all parameters on separate lines. Not the first parameter with the method name and the remainder on separate lines. I dont really care about this personally though.
 2. I don't think we should be putting commas at the beginning like this. It isn't done anywhere else in this code base and actually I've never seen it done before. Just like with enums and arrays, etc commas need to be at the end of the line before.

At some point we really need to write formatting rules in a doc for contributos. For the most part people just follow the C# standard convention as it evolves.

Comment (workgroupengineering) [reply src/Avalonia.Diagnostics/Diagnostics/Views/PropertyValueEditorView.cs:235]: You are right that there would be a need to write some formatting rules.

I used this style of formatting because it makes it easier to read, you can comment out individual parameters without `/* */`, it makes it easier to identify what changes you've added.

consider the following code fragment:

### current style:

```csharp
public static void MyVeryLongMethod(int a /* a coefficient*/, int b /* b coefficient*/, int c /* c coefficient*/, int d /* d coefficient*/, int e /* e coefficient*/)
{
}
```

### code-style rule like `c`

```csharp
public static void MyVeryLongMethod(int a // a coefficient
             , int b // b coefficient
             , int c // c coefficient
             , int d // d coefficient
             , int e // e coefficient
             )
{

}
```

if add parameter f and change c parameter type

### current style:

```diff
-public static void MyVeryLongMethod(int a /* a coefficient*/, int b /* b coefficient*/, int c /* c coefficient*/, int d /* d coefficient*/, int e /* e coefficient*/)
+public static void MyVeryLongMethod(int a /* a coefficient*/, int b /* b coefficient*/, bool c /* c coefficient*/, int d /* d coefficient*/, int e /* e coefficient*/, string? f = default)
{
}
```

###  code-style rule like `c`

```diff
public static void MyVeryLongMethod(int a // a coefficient
             , int b // b coefficient
-            , int c // c coefficient
+            , bool c // c coefficient
             , int d // d coefficient
             , int e // e coefficient
+            , string? f = default
             )
{

}
```
With a code-style rule like `c`, changes are identified faster.

Comment (timunie) [reply src/Avalonia.Diagnostics/Diagnostics/Views/PropertyValueEditorView.cs:235]: Interesting. Doesn't it work also like this ?

```cs
        void TestMe(
            int a, // Comment 1 goes here
            int b, // comment 2
            int c) // comment 3
        {
            Debug.Print("{a} {b} {c}");
        }
```

Comment (workgroupengineering) [reply src/Avalonia.Diagnostics/Diagnostics/Views/PropertyValueEditorView.cs:235]: Yes, but the disadvantage if you add `d` parameter in diff has 3 row changed but only one is significative.

```diff
        void TestMe(
            int a, // Comment 1 goes here
            int b, // comment 2
-           int c, // comment 3
-           int c) // comment 3
+           int d) // comment 4
        {
            Debug.Print("{a} {b} {c}");
        }
```

with code-style rule like c

```csharp
        void TestMe( int a // Comment 1 goes here
            , int b  // comment 2
            , int c // comment 3
            ) 
        {
            Debug.Print("{a} {b} {c}");
        }
```

```diff
        void TestMe( int a // Comment 1 goes here
            , int b  // comment 2
            , int c // comment 3
+           , int d // comment 4
            ) 
        {
            Debug.Print("{a} {b} {c}");
        }
```

Comment (robloo) [reply src/Avalonia.Diagnostics/Diagnostics/Views/PropertyValueEditorView.cs:235]: @workgroupengineering I don't argue that there are good reasons to format the comma as you did. It definitely helps with change tracking on a per-line basis. However, it violates the standard C# convention that goes back decades. I think in this case we need to follow the existing code base.

Comment (workgroupengineering) [reply src/Avalonia.Diagnostics/Diagnostics/Views/PropertyValueEditorView.cs:235]: it's not said that since it's always been like this, you have to continue even though there's probably a better way. That said, as soon as I can, I will change.

Comment (robloo) [reply src/Avalonia.Diagnostics/Diagnostics/Views/PropertyValueEditorView.cs:235]: True, and I say that many times myself! In this case though, I don't think the pros outweigh the cons. (Cons being namely its difficult to read at first and changes the convention used everywhere else)

Comment (workgroupengineering) [reply src/Avalonia.Diagnostics/Diagnostics/Views/PropertyValueEditorView.cs]: Identifying changes more easily, in my opinion is a big pro to improve the quality of the code. That said, I made the changes you suggested.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0036709-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]
