### PR TITLE
Fix creating fields for attached properties called name. closes #12283

### LINKED ISSUE #12283: [Generator] "Name" attached property tries to generate field
**Describe the bug**
Setting an attached property with the name "Name" will cause the Avalonia Generator to generate a field/property for it.
This is not only unexpected but also a huge problem when the name contains e.g. spaces, as the generator than fails and a build error occurs. This happens e.g. with the AutomationProperties.Name, but also with custom attached properties.

**To Reproduce**

1. Copy this control into a xaml file (with Avalonia Generators enabled)
```xaml
<TextBox x:Name="MyTextBox"
       AutomationProperties.Name="This is a textbox"
       local:MyAttachedProperty.Name="my textbox" />
```
2. Try to build
3. See errors

<details>
  <summary>MyAttachedProperty</summary>
  
  ```cs
public class MyAttachedProperty
{
    public static readonly AttachedProperty<string> NameProperty =
        AvaloniaProperty.RegisterAttached<MyAttachedProperty, Control, string>("Name");

    public static string GetName(Control element) => element.GetValue(NameProperty);

    public static void SetName(Control element, string value) => element.SetValue(NameProperty, value);

}
  ```
</details>

**Expected behavior**
No field should be generated for attached property called "Name" (including AutomationProperties.Name), no build error

**Screenshots**
grafik

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 11.0.0

### PR DESCRIPTION
**Pull request by Mrxx99**
## What does the pull request do?
This fixes the issue that the Avalonia.Generators is creating fields for attached proerties that have the name "Name"

## What is the current behavior?
A field is created for attached properties called "Name", leading to compile errors, if they contain characters not valid for field names like spaces. A common use case for this is the `AutomationProperties.Name`. (#12283)

## What is the updated/expected behavior with this PR?
No field is generated for attached properties with name "Name"

## How was the solution implemented (if it's not obvious)?
Filtering out attached properties in XamlNameResolver by checking if `DeclaringType` is different to `TargetType`.

## Checklist

- [x] Added unit tests? -> adjusted existing test
- [ ] Added XML documentation to any related classes? ->not relevant
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation -> not needed

## Breaking changes
Technical yes, if users would have relied on a wrongly generated field, but I would say that is rather unlikely and is easily fixable by the user.

## Obsoletions / Deprecations
none

## Fixed issues
Fixes #12283

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038030-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

File: src/tools/Avalonia.Generators/Common/XamlXNameResolver.cs [hunk 1]
```diff
@@ -89,4 +90,9 @@ private string TryGetFieldModifier(XamlAstObjectNode objectNode)
             _ => _defaultFieldModifier
         };
     }
+
+    private static bool IsAttachedProperty(XamlAstNamePropertyReference namedProperty)
+    {
+        return !namedProperty.DeclaringType.Equals(namedProperty.TargetType);
```
Comment (maxkatz6) [inline src/tools/Avalonia.Generators/Common/XamlXNameResolver.cs:96]: Shouldn't it be IsAssignableFrom ?

Comment (Mrxx99) [reply src/tools/Avalonia.Generators/Common/XamlXNameResolver.cs:96]: If I use this:
```csharp
private static bool IsAttachedProperty(XamlAstNamePropertyReference namedProperty)
{
    return !namedProperty.DeclaringType.GetClrType().IsAssignableFrom(namedProperty.TargetType.GetClrType());
}
```
then the test `XamlXNameResolverTests.Should_Resolve_Types_From_Avalonia_Markup_File_When_Types_Contains_Generic_Arguments` fails.

Everything works fine with the current approach. Here it does not seem to matter that `Name` comes from `StyledElement`, otherwise the tests would fail. I also tested it with the actual nuget packages from the PRBUILD, it solves the problem but still generates the normal field for direct `Name` property.

It would maybe make sense to have a `IsAttachedProperty` method or extension method directly on `XamlAstNamePropertyReference`, but I guess that would need to go into `XamlX`.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038036-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by Mrxx99** [comment]
@maxkatz6 Any idea why integration tests are failing? Seems winappdrive had some connection issues, can these be re-triggered?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038072-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]
