### PR TITLE
Fix DevTools style list not updating correctly

### LINKED ISSUE #9382: DevTools showing styles for the wrong pseudo classes
**Describe the bug**
The DevTools consistently show incorrect styles for the current pseudo classes. When `:pointerover` is active, the styles for `:not(:pointerover)` are shown and vice versa. The style list is initially populated correctly, but becomes inverted on any update to the hover state.

Tested on versions `0.10.18` and `11.0.0-preview3`.
Demonstration: https://www.youtube.com/watch?v=cQD0O5_OoHQ

**To Reproduce**
- Paste the below xaml code into an empty Avalonia project
- Build and run the project
- Open DevTools and navigate to the `Border` element
- Toggle the `:pointerover` pseudo class, either by hovering over the app window or with the checkboxes in DevTools
- The style list will show either the `:pointerover` or `:not(:pointerover)` style, but always the incorrect one

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        x:Class="PseudoClasses.MainWindow"
        Title="PseudoClasses"
        Width="400"
        Height="400">

  <Window.Styles>
    <Style Selector="Border">
      <Setter Property="Background" Value="MediumSeaGreen"/>
    </Style>
    <Style Selector="Border:not(:pointerover)">
      <Setter Property="Background" Value="DodgerBlue"/>
    </Style>
    <Style Selector="Border:pointerover">
      <Setter Property="Background" Value="Crimson"/>
    </Style>
  </Window.Styles>

  <Border HorizontalAlignment="Stretch" VerticalAlignment="Stretch"/>
</Window>
```

**Expected behavior**
When the element is hovered over, the `Border:pointerover` style should be shown in the style list. Conversely, `Border:not(:pointerover)` should be shown when that is not the case.

**Desktop**
- OS: Windows 11 Home, Version 22H2, Build 22621.674
- Version `0.10.18` and `11.0.0-preview3`

### PR DESCRIPTION
**Pull request by AtomCrafty**
## What does the pull request do?
Changes the way the DevTools register for class change notifications so they are updated _after_ the actual style instances.

## What is the current behavior?
The DevTools style list currently does not update properly when the pseudo classes of the selected control change.

## What is the updated/expected behavior with this PR?
The style list now shows the correct styles as active.

## How was the solution implemented (if it's not obvious)?
The issue was that `Avalonia.Diagnostics.ViewModels.ControlDetailsViewModel.UpdateStyles` was run before the actual `StyleInstance`'s `IsActive` property was updated, so the DevTools were always lagging one update behind.

The stack traces revealed that the two notification paths diverged in `Avalonia.Controls.Classes`'s implementation of `Avalonia.Controls.IPseudoClasses.Add`. The DevTools used to hook directly into the `AvaloniaList`'s `CollectionChanged` event, while the style instance is notified through a style activator, which is registered as a `ClassesChangedListener` and therefore gets notified later.

The fix was simply to make `ControlDetailsViewModel` receive updates via an `IClassesChangedListener` instead of through the backing list's `CollectionChanged` event.

I also included a second commit with some typo fixes. Not sure if this is the right place for them.

```
Avalonia.Diagnostics.dll!Avalonia.Diagnostics.ViewModels.ControlDetailsViewModel.UpdateStyles() Line 342	C#
Avalonia.Diagnostics.dll!Avalonia.Diagnostics.ViewModels.ControlDetailsViewModel.OnClassesChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
Avalonia.Base.dll!Avalonia.Collections.AvaloniaList<string>.NotifyAdd(string item, int index)
Avalonia.Base.dll!Avalonia.Collections.AvaloniaList<string>.Add(string item)
Avalonia.Base.dll!Avalonia.Controls.Classes.Avalonia.Controls.IPseudoClasses.Add(string name)
Avalonia.Base.dll!Avalonia.Controls.PseudolassesExtensions.Set(Avalonia.Controls.IPseudoClasses classes, string name, bool value)

Avalonia.Base.dll!Avalonia.Styling.StyleInstance.ActivatorChanged(bool value)
Avalonia.Base.dll!Avalonia.Styling.StyleInstance.Avalonia.Styling.Activators.IStyleActivatorSink.OnNext(bool value, int tag)
Avalonia.Base.dll!Avalonia.Styling.Activators.StyleActivatorBase.PublishNext(bool value)
Avalonia.Base.dll!Avalonia.Styling.Activators.StyleClassActivator.Avalonia.Controls.IClassesChangedListener.Changed()
Avalonia.Base.dll!Avalonia.Controls.Classes.NotifyChanged()
Avalonia.Base.dll!Avalonia.Controls.Classes.Avalonia.Controls.IPseudoClasses.Add(string name)
Avalonia.Base.dll!Avalonia.Controls.PseudolassesExtensions.Set(Avalonia.Controls.IPseudoClasses classes, string name, bool value)
```
```cs
// From src/Avalonia.Base/Controls/Classes.cs, line 284
void IPseudoClasses.Add(string name)
{
    if (!Contains(name))
    {
        base.Add(name);     // DevTools view model was updated here
        NotifyChanged();    // StyleInstance.IsActive is updated here
    }
}
```

## Fixed issues
Fixes #9382

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=9402) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=9402) before we can accept your contribution.<br/><br/>:x: AtomCrafty [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=9402)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=9402) it.</sub>

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025966-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

File: src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlDetailsViewModel.cs [hunk 1]
```diff
@@ -46,7 +47,8 @@ public ControlDetailsViewModel(TreePageViewModel treePage, IAvaloniaObject avalo
 
             if (avaloniaObject is StyledElement styledElement)
             {
-                styledElement.Classes.CollectionChanged += OnClassesChanged;
+                _classesChangedListener = new ActionClassesChangedListener(OnClassesChanged);
```
Comment (grokys) [inline src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlDetailsViewModel.cs:50]: It's a minor thing really, but couldn't we implement `IClassesChangedListener` on `ControlDetailsViewModel` instead of creating an inner object?

Comment (AtomCrafty) [reply src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlDetailsViewModel.cs:50]: Yeah, no problem. I originally chose the delegating implementation because I thought `Changed` was a bit nondescript as a method name, but with an explicit interface implementation its purpose becomes obvious again. Alternatively I could change the name to somethings like `ClassesChanged`, which would be fine since it's an internal interface with only one other implementor.

While I'm touching these files anyway I also did some general cleanup, feel free to drop those commits if you think that doesn't belong in this PR.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025976-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]
