### PR TITLE
FontLoading adjustments

### LINKED ISSUE #19535: ControlCatalog.Desktop crashes when switching to TextBox/TextBlock Tab
### Describe the bug

I used the master branch to compile and run Control Catalog.Desktop with Visual Studio, and the crash described in the title occurred. This happens regardless of debug or release mode. There is no such issue when compiling and running with 11.3.4 branch.

**Debug mode:** Crash in \Avalonia\src\Avalonia.Base\Media\TextFormatting\FormattingObjectPool.cs

Image

**Release mode:** Crash in \Avalonia\src\Avalonia.Base\Media\Typeface.cs

Image

### To Reproduce

1. Compile and run ControlCatalog.Desktop
2. Click TextBox or TextBlock Tab

### Expected behavior

_No response_

### Avalonia version

master

### OS

Windows

### Additional context

Windows 11 10.0.26100.4946

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?

This PR ensures that we validate the name part of a constructed FontFamily, allowing only specific formats.

`public FontFamily(Uri? baseUri, string name)`

The name must contain a `/` or be an absolute URI string to reference a non-system font. Everything else will be resolved as a system font.
## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues

Fixes: #19535

### CODE REVIEW

**Comment by MrJul** [comment]
@Gillibald The exception from #19535 still happens after this PR.
It seems that "Comic Sans MS" is trying to be resolved with local keys, which doesn't work.
That said, the error seems a bit orthogonal to the validation added in this PR, which should imo be merged.

(Also, there's another debug-only exception about a `RentedList` not being returned - but this can be tackled later.)

**Comment by Gillibald** [comment]
That error usually happens when an exception is thrown during text layout

File: tests/Avalonia.UnitTests/HarfBuzzFontManagerImpl.cs [hunk 1]
```diff
@@ -14,11 +14,11 @@ public class HarfBuzzFontManagerImpl : IFontManagerImpl
...
 
         private static readonly Typeface _defaultTypeface =
-            new Typeface(new FontFamily(new Uri("resm:Avalonia.UnitTests.Assets?assembly=Avalonia.UnitTests", UriKind.Absolute), "Noto Mono"));
+            new Typeface(new FontFamily("resm:Avalonia.UnitTests.Assets?assembly=Avalonia.UnitTests#Noto Mono"));
         private  static readonly Typeface _italicTypeface =
-            new Typeface(new FontFamily(new Uri("resm:Avalonia.UnitTests.Assets?assembly=Avalonia.UnitTests", UriKind.Absolute), "Noto Sans"));
+            new Typeface(new FontFamily("resm:Avalonia.UnitTests.Assets?assembly=Avalonia.UnitTests#Noto Sans"));
         private  static readonly Typeface _emojiTypeface =
-            new Typeface(new FontFamily(new Uri("resm:Avalonia.UnitTests.Assets?assembly=Avalonia.UnitTests"), "Twitter Color Emoji"));
+            new Typeface(new FontFamily("resm:Avalonia.UnitTests.Assets?assembly=Avalonia.UnitTests#Twitter Color Emoji"));
```
Comment (maxkatz6) [inline tests/Avalonia.UnitTests/HarfBuzzFontManagerImpl.cs:21]: We don't really support resm anymore. Is there a point in testing with it?

Comment (maxkatz6) [reply tests/Avalonia.UnitTests/HarfBuzzFontManagerImpl.cs:21]: Nevermind, we still have some code for it. Especially for fonts.

Comment (maxkatz6) [reply tests/Avalonia.UnitTests/HarfBuzzFontManagerImpl.cs:21]: I was refering to this previously https://github.com/AvaloniaUI/Avalonia/pull/9220

Comment (Gillibald) [reply tests/Avalonia.UnitTests/HarfBuzzFontManagerImpl.cs:21]: AvaloniaResource needs a special generator, if I am not mistaken

**Review by MrJul — APPROVED** [review]
System font parsing is now ok, but relative paths aren't working anymore.

Examples of paths which now fail but used to work:
 - `Some/Path/#FontName`
 - `./Some/Path/#FontName`
 - `../Some/Path/#FontName`

**Review by MrJul — CHANGES_REQUESTED** [review]
Wrong button!

**Review by MrJul — APPROVED** [review]
LGTM!
