### PR TITLE
Fix fetching neutral value in animations.

### LINKED ISSUE #6063: Animation does not correctly detect neutral value.
**Describe the bug**

The following XAML does not pick up the fact that the neutral value of the `Fill` property is `Red`:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'
        x:Class="Sandbox.MainWindow">
    <Window.Styles>
        <Style Selector="Rectangle.foo">
            <Setter Property="Fill" Value="Red" />
        </Style>
        <Style Selector="Rectangle.animate">
            <Style.Animations>
                <Animation Duration="0:0:1" PlaybackDirection="Alternate" IterationCount="Infinite">
                    <KeyFrame Cue="100%">
                        <Setter Property="Fill" Value="Yellow"/>
                    </KeyFrame>
                </Animation>
            </Style.Animations>
        </Style>
    </Window.Styles>
    <Canvas VerticalAlignment="Top" HorizontalAlignment="Left" Width="100" Height="50" Canvas.Left="0" Canvas.Top="0">
        <Rectangle Classes="foo animate" Canvas.Top="0" Canvas.Left="0" Width="50" Height="50"/>
    </Canvas>
</Window>
```

Adding an additional `KeyFrame` makes it work:

```
                    <KeyFrame Cue="0%">
                        <Setter Property="Fill" Value="Red"/>
                    </KeyFrame>
                    <KeyFrame Cue="100%">
                        <Setter Property="Fill" Value="Yellow"/>
                    </KeyFrame>
```

But we should be picking up `Red` as the neutral value for the animation here automatically I think?

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Animators fetched the neutral value when the animation is instantiated but did not update the neutral value if it's updated after that.

#6063 was caused by the fact that the neutral value does not take effect until the batch update due to styling has finished on the control, which is _after_ the animation has been instantiated.

Listen for changes on the property and if the change is not an animated value change, update the neutral value.

This isn't perfect because it won't react to changes to the neutral value while the animation is actually running and producing values because `PropertyChanged` events don't get fired for non-active values: for that we'd need to hook into `OnPropertyChangedCore`. But this at least fixes the simple case of the initial neutral value.

We REALLY need unit tests for animation. Units tests would have caught this.

## Fixed issues

Fixes #6063.

### CODE REVIEW

**Review by jmacato — APPROVED** [review]
LGTM!

File: src/Avalonia.Animation/AnimationInstance`1.cs [hunk 1]
```diff
@@ -45,8 +46,9 @@ public AnimationInstance(Animation animation, Animatable control, Animator<T> an
             _onCompleteAction = OnComplete;
             _interpolator = Interpolator;
             _baseClock = baseClock;
-            _neutralValue = (T)_targetControl.GetValue(_animator.Property);
+            control.PropertyChanged += ControlPropertyChanged;
```
Comment (MarchingCube) [inline src/Avalonia.Animation/AnimationInstance`1.cs:49]: I think this will keep this instance alive since you are not unsubscribing.

Comment (grokys) [reply src/Avalonia.Animation/AnimationInstance`1.cs:49]: Ah damn, I thought I added that but looks like I forgot. Will fix.
