### PR TITLE
Fix for #2544

### LINKED ISSUE #2544: Avalonia Resource lookup fails when assembly has space in its name
From https://github.com/AvaloniaUI/AvaloniaVS/issues/101:

```
21:17:07.117 [Error] 9864 <= "Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Universal%20Boottle, Culture=neutral, PublicKeyToken=null'. Nie moľna odnale«† okrelonego pliku."
21:17:07.119 [Error] 9864 <= "   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)"
21:17:07.120 [Error] 9864 <= "   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)"
21:17:07.121 [Error] 9864 <= "   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark, IntPtr pPrivHostBinder)"
21:17:07.122 [Error] 9864 <= "   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark)"
21:17:07.123 [Error] 9864 <= "   at System.Reflection.Assembly.Load(String assemblyString)"
21:17:07.125 [Error] 9864 <= "   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(String name) in D:\a\1\s\src\Shared\PlatformSupport\AssetLoader.cs:line 238"
```

Looks like we're no de-URLencoding our assembly name before trying to find the assembly.

### PR DESCRIPTION
**Pull request by matthias-hoste**
## What does the pull request do?
It fixes a bug for apps with spaces in their name.

## What is the current behavior?
The assembly name is currently not url decoded before trying to load it.

## What is the updated/expected behavior with this PR?
It will correctly url decode it so it can load assemblies with spaces in their name.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues
Fixes #2544

### CODE REVIEW

File: src/Shared/PlatformSupport/AssetLoader.cs [hunk 1]
```diff
@@ -242,6 +242,7 @@ private AssemblyDescriptor GetAssembly(string name)
                     throw new InvalidOperationException(
                         $"Assembly {name} needs to be referenced and explicitly loaded before loading resources");
 #else
+                    name = HttpUtility.UrlDecode(name);
```
Comment (kekekeks) [inline src/Shared/PlatformSupport/AssetLoader.cs]: https://docs.microsoft.com/en-us/dotnet/api/system.uri.unescapedatastring?view=netframework-4.8

Comment (lifecoder-phoenix) [reply src/Shared/PlatformSupport/AssetLoader.cs]: Thanks for pointing that out, I did not know that exists

**Review by jmacato — APPROVED** [review]
this looks good to me
