### PR TITLE
Fix ItemsRepeater leak

### LINKED ISSUE #4599: ItemsRepeater controls won't be GCd
I've found at least two ways that cause `ItemsRepeater` controls to stay alive indefinitely.
1. `LayoutManager._effectiveViewportChangedListeners` can hold old `ItemsRepeater` - I need to investigate this one further.
2. `ItemsRepeater.Layout` has `StackLayout` as a default value which causes all default created `ItemsRepeater` controls to subscribe to `MeasureInvalidated` forever.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

As described in #4599, `ItemsRepeater` instances were leaking. Fix this by:

- Cleaning up `EffectiveViewportChanged` subscriptions before calling `OnDetachedFromVisualTree` so that (un)subscribing to the `EffectiveViewportChanged`  event in `OnDetachedFromVisualTree` doesn't cause a leak
- Use weak event handlers for `AttachedLayout.MeasureInvalidated`/`ArrangeInvalidated`. Seems that C++/WinRT uses weak event handlers by default so we need to do the same here.

## Checklist

- [x ] Added unit tests (if possible)?

## Fixed issues

Fixes #4599

### CODE REVIEW

File: tests/Avalonia.LeakTests/ControlTests.cs [hunk 1]
```diff
@@ -552,6 +552,42 @@ public void Path_Is_Freed()
...
+                    return window;
+                };
+
+                var result = run();
+
+                dotMemory.Check(memory =>
+                    Assert.Equal(0, memory.GetObjects(where => where.Type.Is<ItemsRepeater>()).ObjectsCount));
+
+                // We are keeping geometry alive to simulate a resource that outlives the control.
+                GC.KeepAlive(geometry);
```
Comment (MarchingCube) [inline tests/Avalonia.LeakTests/ControlTests.cs:587]: copy pasta?

File: src/Avalonia.Controls/Repeater/ItemsRepeater.cs [hunk 2]
```diff
@@ -681,8 +681,15 @@ private void OnLayoutChanged(AttachedLayout oldValue, AttachedLayout newValue)
             if (oldValue != null)
             {
                 oldValue.UninitializeForContext(LayoutContext);
-                oldValue.MeasureInvalidated -= InvalidateMeasureForLayout;
-                oldValue.ArrangeInvalidated -= InvalidateArrangeForLayout;
+
+                WeakEventHandlerManager.Unsubscribe<EventArgs, ItemsRepeater>(
+                    oldValue,
+                    nameof(newValue.MeasureInvalidated),
```
Comment (MarchingCube) [inline src/Avalonia.Controls/Repeater/ItemsRepeater.cs:687]: This `newValue` is a bit confusing here. Can you use `nameof(AttachedLayout.MeasureInvalidated)` ?

**Review by MarchingCube — APPROVED** [review]
LGTM with two small nits.

File: src/Avalonia.Controls/Repeater/ItemsRepeater.cs (hunk 2 above)
Comment (grokys) [reply src/Avalonia.Controls/Repeater/ItemsRepeater.cs:687]: Sure. I used this because it was roughly analogous to `newValue.MeasureInvalidated += ...` but I don't really have any preference.
