### PR TITLE
Cancel animations when selector turns false & ProgressBar IsIndeterminate fix

### LINKED ISSUE #1864: Changing ProgressBar.IsIndeterminate via Binding doesn't stop the marquee style
The marquee will grow larger and larger though as progress increases

### PR DESCRIPTION
**Pull request by jmacato**
- What does the pull request do?
  - Stops a looping animation whenever its selector is invalidated/turned false.
- What is the current behavior?
  - Looping animations simply overlap with each other and does not stop when selectors changes state.

Fixes #1864

### CODE REVIEW

File: src/Avalonia.Animation/Animator`1.cs [hunk 1]
```diff
@@ -37,12 +37,29 @@ public virtual IDisposable Apply(Animation animation, Animatable control, IObser
              if (!_isVerifiedAndConverted)
                 VerifyConvertKeyFrames();
 
-            return match
+            var matchStream = match
```
Comment (grokys) [inline src/Avalonia.Animation/Animator`1.cs]: I _think_ there might be an easier way to do this:

```
            return match
                .DistinctUntilChanged()
                .Select(x => x ? RunKeyFrames(animation, control, onComplete) : null)
                .Buffer(2, 1)
                .Where(x => x.Count > 1)
                .Subscribe(x => x[0]?.Dispose());
```

What that should do is create an old/new pair of `IDisposable`s and if the old value is non-null, call `Dispose` on it. Does that seem right to you?

Comment (jmacato) [reply src/Avalonia.Animation/Animator`1.cs]: Never knew about `Buffer()` before, i learned something today :smile: I'll test that one out sir

**Comment by jmacato** [comment]
Seems like ProgressBar isn't handling `IsIndeterminate` when it changes.. I'll fix that here instead.

File: src/Avalonia.Animation/Animator`1.cs [hunk 2]
```diff
@@ -28,21 +28,25 @@ public abstract class Animator<T> : AvaloniaList<AnimatorKeyFrame>, IAnimator
...
-                {
-                    var timerObs = RunKeyFrames(animation, control, onComplete);
-                });
+                     .DistinctUntilChanged()
+                     .Select(x => x ? RunKeyFrames(animation, control, onComplete) : null)
+                     .Buffer(2, 1)
+                     .Where(x => x.Count > 1)
+                     .Subscribe(x =>
+                        {
+                            if (animation.RepeatCount.IsLoop)
```
Comment (grokys) [inline src/Avalonia.Animation/Animator`1.cs]: Don't we want to cancel non-looping animations when the selector no longer matches?

Comment (jmacato) [reply src/Avalonia.Animation/Animator`1.cs]: Right, i've double-checked with CSS and it does cancel animations when the selector turns false

File: src/Avalonia.Animation/Animator`1.cs [hunk 3]
```diff
@@ -28,21 +28,20 @@ public abstract class Animator<T> : AvaloniaList<AnimatorKeyFrame>, IAnimator
...
 
-            return match
-                .Where(p => p)
-                .Subscribe(_ =>
-                {
-                    var timerObs = RunKeyFrames(animation, control, onComplete);
-                });
+            return match.DistinctUntilChanged()
+                        .Select(x => x ? RunKeyFrames(animation, control, onComplete) : null)
+                        .Buffer(2, 1)
```
Comment (jkoritzinsky) [inline src/Avalonia.Animation/Animator`1.cs]: Are we sure that `.Buffer(2, 1)` does what we want? Based on the [System.Reactive documentation](http://reactivex.io/documentation/operators/buffer.html) it doesn't seem right. I think we might need more of a custom observable similar to https://github.com/jkoritzinsky/AvaloniaAV/blob/master/AvaloniaAV/ObservableExtensions.cs but based off `LightweightObservableBase` to actually do what we want.

**Review by jkoritzinsky — CHANGES_REQUESTED** [review]

File: src/Avalonia.Base/Reactive/DisposeOnNextObservable.cs [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+{
+    public class DisposeOnNextObservable<T> : LightweightObservableBase<T>, IObserver<T> where T : IDisposable
+    {
+        private IDisposable lastValue;
+
+        private void ValueNext(T value)
+        {
+            this.PublishNext(value);
+            lastValue?.Dispose();
+            lastValue = value;
```
Comment (jmacato) [inline src/Avalonia.Base/Reactive/DisposeOnNextObservable.cs]: I'm having problems making `WeakReference` work with this. I dont want to use this direct-store method as it looks hackish...

File: src/Avalonia.Animation/Animator`1.cs [hunk 5]
```diff
@@ -28,21 +31,20 @@ public abstract class Animator<T> : AvaloniaList<AnimatorKeyFrame>, IAnimator
...
                 VerifyConvertKeyFrames();
 
-            return match
-                .Where(p => p)
-                .Subscribe(_ =>
-                {
-                    var timerObs = RunKeyFrames(animation, control, onComplete);
-                });
+            return match.DistinctUntilChanged()
+                        .ObserveOn(Avalonia.Threading.AvaloniaScheduler.Instance)
```
Comment (jmacato) [inline src/Avalonia.Animation/Animator`1.cs]: This seems to be necessary since i'm having LinkedList exceptions on Bindings whenever the animation cancels...

Comment (jmacato) [reply src/Avalonia.Animation/Animator`1.cs]: Ahh this is just delaying the inevitable; that exception still happens somehow.

File: src/Avalonia.Animation/AnimationInstance`1.cs [hunk 6]
```diff
@@ -188,10 +188,7 @@ private void InternalStep(TimeSpan systemTime)
 
             if (!_isLooping)
             {
-                if (_currentIteration > _repeatCount)
-                    DoComplete();
-
-                if (time > iterationEndpoint)
+                if ((_currentIteration > _repeatCount) | (time > iterationEndpoint))
```
Comment (Kryptos-FR) [inline src/Avalonia.Animation/AnimationInstance`1.cs]: WARN: byte operator `|` instead of bool operator `||`.

bool operator is preferred as it can skip the right side evaluation when the left side is `true`.

Comment (jmacato) [reply src/Avalonia.Animation/AnimationInstance`1.cs]: No i deliberately set it to eager evaluation since that code needs to check the right-side condition

Comment (jkoritzinsky) [reply src/Avalonia.Animation/AnimationInstance`1.cs]: If there's no side-effects in either operand then there's no reason not to use lazy evaluation.

Comment (jmacato) [reply src/Avalonia.Animation/AnimationInstance`1.cs]: @jkoritzinsky right, i forgot about that. I just wanted to be doubly-sure that the conditions will be evaluated

Comment (jkoritzinsky) [reply src/Avalonia.Animation/AnimationInstance`1.cs]: They will both be evaluated. Can you either switch it to use `||` or add a comment on why it needs to be `|`?

**Review by grokys — COMMENTED** [review]
This is called an "Observable" but it only implements `IObserver` and in addition, the variable it's assigned to is called `subject`. Probably should decide what it is ;)

File: src/Avalonia.Animation/DisposeAnimationInstanceObservable.cs [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+using Avalonia.Collections;
+using Avalonia.Data;
+using Avalonia.Reactive;
+
+namespace Avalonia.Animation
+{
+    /// <summary>
+    /// Manages the lifetime of animation instances as determined by its selector state.
+    /// </summary>
+    internal class DisposeAnimationInstanceObservable<T> : IObserver<bool>, IDisposable
```
Comment (grokys) [inline src/Avalonia.Animation/DisposeAnimationInstanceObservable.cs]: This is called an "Observable" but it only implements `IObserver` and in addition, the variable it's assigned to is called `subject`. Probably should decide what it is ;)

**Review by grokys — COMMENTED** [review]
This can be merged with the method above as they're exactly the same. Maybe just call them `UpdateIndicator` like the method they call?

File: src/Avalonia.Animation/DisposeAnimationInstanceObservable.cs (hunk 7 above)
Comment (jmacato) [reply src/Avalonia.Animation/DisposeAnimationInstanceObservable.cs]: Oof, sorry. Forgot to rename that class name to Subject

File: src/Avalonia.Animation/AnimationInstance`1.cs (hunk 6 above)
Comment (jmacato) [reply src/Avalonia.Animation/AnimationInstance`1.cs]: I'll just change it back to `||` since my justification for not using that is already moot

**Review by jkoritzinsky — APPROVED** [review]

File: src/Avalonia.Animation/DisposeAnimationInstanceObservable.cs (hunk 7 above)
Comment (grokys) [reply src/Avalonia.Animation/DisposeAnimationInstanceObservable.cs]: Hmm but it's not a subject because a subject implements both `IObserver` and `IObservable`. Sorry, I realise this is getting a bit nit-picky!
